// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quuovnvafnrbcxpglvfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1dW92bnZhZm5yYmN4cGdsdmZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTE4NjgsImV4cCI6MjA3MzMyNzg2OH0.S1OTWXK4syI0w3oCSa4c3MMxk5buJz3uw2YN55tbjFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});